"""GitHub issue templates for incident reports."""

INCIDENT_ISSUE_TEMPLATE = """## 🚨 Production Incident Report

**Generated by:** AI DevOps Incident Copilot
**Detected at:** {detected_at}
**Severity:** {severity}
**Service:** {service_name}
**Anomaly Type:** {anomaly_type}
**Confidence Score:** {confidence_score:.0%}

---

### 📋 Summary

{summary}

---

### 🔍 Root Cause Analysis

{root_cause}

---

### 💥 Impact

{impact}

---

### 🔧 Suggested Fixes

{fixes}

---

### 🛡️ Prevention Steps

{prevention}

---

### 📊 Related Log Snippets

```
{log_snippets}
```

---

### 📈 Detection Metrics

{metrics}

---

<sub>This issue was automatically generated by the AI DevOps Incident Copilot.
RCA was generated using {llm_mode} analysis. Review and validate before taking action.</sub>
"""
