"""Pydantic models and SQLAlchemy ORM models."""

from __future__ import annotations

import enum
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field
from sqlalchemy import Column, DateTime, Enum, Integer, String, Text, Float, create_engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from src.config import get_settings


# ─────────────────────────────────────────────
# SQLAlchemy Models
# ─────────────────────────────────────────────

class Base(DeclarativeBase):
    """SQLAlchemy declarative base."""
    pass


class IncidentSeverity(str, enum.Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class IncidentStatus(str, enum.Enum):
    OPEN = "open"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"


class IncidentRecord(Base):
    """SQLAlchemy model for storing incidents."""

    __tablename__ = "incidents"

    id = Column(Integer, primary_key=True, autoincrement=True)
    title = Column(String(500), nullable=False)
    severity = Column(Enum(IncidentSeverity), default=IncidentSeverity.MEDIUM)
    status = Column(Enum(IncidentStatus), default=IncidentStatus.OPEN)
    service_name = Column(String(200), nullable=False)
    anomaly_type = Column(String(200), nullable=False)
    raw_logs = Column(Text, nullable=True)
    root_cause_analysis = Column(Text, nullable=True)
    suggested_fixes = Column(Text, nullable=True)
    llm_summary = Column(Text, nullable=True)
    github_issue_url = Column(String(500), nullable=True)
    confidence_score = Column(Float, default=0.0)
    detected_at = Column(DateTime, default=datetime.utcnow)
    resolved_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)


# ─────────────────────────────────────────────
# Pydantic Schemas
# ─────────────────────────────────────────────

class LogEntry(BaseModel):
    """A single log line from a Kubernetes pod."""

    timestamp: datetime
    namespace: str = "default"
    pod_name: str
    container_name: str
    log_level: str  # INFO, WARN, ERROR, FATAL
    message: str
    metadata: dict = Field(default_factory=dict)


class AnomalyEvent(BaseModel):
    """Detected anomaly from log analysis."""

    anomaly_type: str
    severity: IncidentSeverity
    service_name: str
    description: str
    affected_pods: list[str] = Field(default_factory=list)
    related_logs: list[LogEntry] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0, default=0.5)
    detected_at: datetime = Field(default_factory=datetime.utcnow)
    metrics: dict = Field(default_factory=dict)


class RCAReport(BaseModel):
    """Root Cause Analysis report generated by LLM."""

    incident_title: str
    summary: str
    root_cause: str
    impact: str
    suggested_fixes: list[str]
    prevention_steps: list[str]
    confidence_score: float = Field(ge=0.0, le=1.0, default=0.5)
    raw_llm_response: str = ""


class IncidentCreate(BaseModel):
    """Schema for creating an incident."""

    title: str
    severity: IncidentSeverity
    service_name: str
    anomaly_type: str
    raw_logs: Optional[str] = None
    root_cause_analysis: Optional[str] = None
    suggested_fixes: Optional[str] = None
    llm_summary: Optional[str] = None
    confidence_score: float = 0.0


class IncidentResponse(BaseModel):
    """Schema for incident API responses."""

    id: int
    title: str
    severity: IncidentSeverity
    status: IncidentStatus
    service_name: str
    anomaly_type: str
    raw_logs: Optional[str] = None
    root_cause_analysis: Optional[str] = None
    suggested_fixes: Optional[str] = None
    llm_summary: Optional[str] = None
    github_issue_url: Optional[str] = None
    confidence_score: float
    detected_at: datetime
    created_at: datetime

    model_config = {"from_attributes": True}


class PipelineStatus(BaseModel):
    """Status of the incident detection pipeline."""

    simulator_running: bool = False
    detector_running: bool = False
    total_logs_processed: int = 0
    total_anomalies_detected: int = 0
    total_incidents_created: int = 0
    last_scan_at: Optional[datetime] = None
